import Header from "./_component/Header";
import Nav from "./_component/Nav";
import Footer from "./_component/Footer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/global.css";
import styles from "../styles/common.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Nav />
        <div className={styles.pageContainer}>
          <div className={styles.inner}>
            <Header />
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
